### ISSUE TITLE
Crashes at wakeup

### ISSUE THREAD

**Issue by vishesh** [vishesh/sealnote#25]
Bunch of reports with this stacktrace. Might be happening because we don't persist password, and during wakeup its gone from memory.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.twistedplane.sealnote/com.twistedplane.sealnote.NoteActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7325)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at com.twistedplane.sealnote.data.Note.convertToTagSet(Note.java:118)
	at com.twistedplane.sealnote.data.Note.readFromParcel(Note.java:97)
	at com.twistedplane.sealnote.data.Note.<init>(Note.java:76)
	at com.twistedplane.sealnote.data.Note$1.createFromParcel(Note.java:250)
	at com.twistedplane.sealnote.data.Note$1.createFromParcel(Note.java:248)
	at android.os.Parcel.readParcelable(Parcel.java:2367)
	at android.os.Parcel.readValue(Parcel.java:2264)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
	at android.os.BaseBundle.getBoolean(BaseBundle.java:659)
	at android.app.Activity.restoreHasCurrentPermissionRequest(Activity.java:7153)
	at android.app.Activity.performCreate(Activity.java:6903)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
	... 9 more
```

```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: Password null or not acceptable
	at com.twistedplane.sealnote.data.DatabaseHandler.update(DatabaseHandler.java:84)
	at com.twistedplane.sealnote.data.DatabaseHandler.getWritableDatabase(DatabaseHandler.java:110)
	at com.twistedplane.sealnote.data.DatabaseHandler.getReadableDatabase(DatabaseHandler.java:115)
	at com.twistedplane.sealnote.data.DatabaseHandler.getNotesCursor(DatabaseHandler.java:558)
	at com.twistedplane.sealnote.data.AdapterLoader.loadInBackground(AdapterLoader.java:30)
	at com.twistedplane.sealnote.data.AdapterLoader.loadInBackground(AdapterLoader.java:13)
	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
```

**Comment by rohitramkumar308** [comment]
I would like to work on this one.

**Comment by akshatgoel** [comment]
@rohitramkumar308 That would be appreciated. Thanks for your contribution!

**Comment by rohitramkumar308** [comment]
What are the steps to replicate this issue and are there any contribution guide lines ?
